### ISSUE TITLE
create_function() is deprecated

### ISSUE THREAD

**Issue by dennis173** [MPAT-eu/MPAT-plugins#3]
Deprecated: Function create_function() is deprecated in MPAT-core/web/app/plugins/mpat-plugins/ContentManagement/PageManagement.php

Since PHP 7.2 this function is deprecated(http://php.net/manual/de/function.create-function.php)
Possible solution http://php.net/manual/de/functions.anonymous.php

**Comment by campino-rocks** [comment]
Is there a solution for this problem?

**Comment by jcdufourd** [comment]
issue fixed on master
